language: python
python:
  - "3.5"
install:
  - pip install pytest pytest-cov
  - pip install coveralls
script:
  - python3 -m unittest
  - pytest --doctest-modules --cov . --cov-report term-missing
after_success:
  - coveralls
